### ISSUE TITLE
pytorch model

### ISSUE THREAD

**Issue by mahmodDAHOL** [treeebooor/object-remove#1]
This is an amazing work, but the link of the model contain only tf model, so it didn't work and it is give me this error:
Traceback (most recent call last):
  File "/content/object-remove/./src/main.py", line 32, in <module>
    deepfill = Generator(checkpoint=deepfill_weights_path, return_flow=True)
  File "/content/object-remove/src/models/deepFill.py", line 306, in __init__
    self.load_state_dict(generator_state_dict, strict=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:

so where is the problem ?
i think that i have to use the pytorch copy of the model.

**Comment by treeebooor** [comment]
Hey Mahmod,
Seems like the link changed. I've updated it for the pytorch model.
